### ISSUE TITLE
jail - time keep counting into negative after jail time is up and player is released from jail

### ISSUE THREAD

**Issue by tompok76** [CyberCube-hk/Jail#11]
time keep counting into negative after kail time is up and player is released from jail and cant move or do anything.
when i unjail or player bail, everything works perfect but relased when times up doenst.
i use 14.01 07:32:46 [Server] Server thread/INFO Plugins (16): EconomyPShop v2.0.2, ItemCloud v1.3, Slapper v1.2.8, SimpleAuth v1.7.1, EconomyAPI v2.0.9, VoteReward v2.1, EconomyShop v2.0.7, TapToDo v2.2.1, essentialsTP v1.1.0, WorldProtect v2.2.0, EconomySell v2.0.7, WorldEditArt v1.0.0_beta_dev_#048, BlockSniffer v1.0.0, SimpleAuthHelper v2.0.4, EconomyLand v2.0.9, Jail v2.0.3

and bleeding 55
any message in a console appeared,
pls help

and this plugin is very awesome! thaks a lot!
t c tomas

**Comment by hoyinm14mc** [comment]
I don't seem to have this problem.. Can you show me some screenshots?

**Comment by tompok76** [comment]
Thank your for your care, screenshot attached

**Comment by astersx** [comment]
This happened too to me,  but i tought it got fixed....

**Comment by hoyinm14mc** [comment]
@astersx Is it happening in v2.1.2, still?

**Comment by hoyinm14mc** [comment]
@astersx Are you against this plugin?

**Comment by astersx** [comment]
Not really!!  But servers who use this plugin are burned :(!!!  

I still have my prison build and wait for others to post a issue "My server burned",  so you can fix that!!!

I cant use this plugin until it gets fixed!!  Servers timed out if they use this plugin!!

**Comment by tompok76** [comment]
How can I get 2.1.2 version? thks for reply, have a nice day, tom

**Comment by hoyinm14mc** [comment]
@tompok76 https://github.com/cybercube-hk/jail/releases/

**Comment by tompok76** [comment]
Oh you are the man, everything works well thanks to you!
Its realy good plugin, all players are now like a angels :dancer: 
thank you and have a nice day,
Tomas
