### ISSUE TITLE
Crash on Paying Bail on Sign

### ISSUE THREAD

**Issue by BobbyTowers** [CyberCube-hk/Jail#12]
The server keeps crashing when players hit the bail sign trying to pay bail.

[6crFew0j.txt](https://github.com/CyberCube-hk/Jail/files/96959/6crFew0j.txt)

**Comment by hoyinm14mc** [comment]
This problem was fixed in v2.1.2. Download it here: https://github.com/CyberCube-hk/Jail/releases/download/v2.1.2/Jail_v2.1.2.phar
