### ISSUE TITLE
Bail amount goes up automatically when in jail.

### ISSUE THREAD

**Issue by BobbyTowers** [CyberCube-hk/Jail#13]
When you're in jail and you look at the info on the screen for time and bail. The bail keeps adding money automatically and doesn't stop.

**Comment by hoyinm14mc** [comment]
That is impossible. I've looked into the code, the bail money is forced to count down.

**Comment by BobbyTowers** [comment]
![screenshot_2016-01-21-22-44-49](https://cloud.githubusercontent.com/assets/12857229/12501930/20e4f8e6-c091-11e5-9079-b8360848b3a8.png)

Still does it and now it spams times up and you've be unjailed.

**Comment by BobbyTowers** [comment]
[22:46:15] warning> RuntimeException: "filesize(): stat failed for C:\Users\Bobby-Foo\Documents\MCPE SQL\plugins\Jail/players.yml" (E_WARNING) in "/Jail_v2.1.2.phar/src/hoyinm14mc/jail/Jail" at line 101
[22:46:15] system> Disabling Jail v2.1.2

**Comment by hoyinm14mc** [comment]
The time there isn't going up. It's decreasing.
The unjail process has been cancelled by a plugin which has conflict with the Jail plugin. Ask the plugin developer of the plugin which blocks players to unjail, to support Jail.
By the way, the problems which you've mentioned were mentioned by others already.

**Comment by BobbyTowers** [comment]
All the problems have been fixed in the new update.
