### ISSUE TITLE
[Server] Server thread/INFO Disabling Jail v2.1.2

### ISSUE THREAD

**Issue by tompok76** [CyberCube-hk/Jail#15]
Oh a new issue! Im sorry...

Ive tried to run only jail pluing on the server and with my regualy running plugins but ive got the same:
---------------------
22.01 04:43:15 [Server] Server thread/INFO Disabling Jail v2.1.2
22.01 04:43:15 [Server] Server thread/WARNING RuntimeException: "filesize(): stat failed for /plugins/Jail/players.yml" (E_WARNING) in "/Jail_v2.1.2.phar/src/hoyinm14mc/jail/Jail" at line 101
--------------------

I can run the server without it... but its good idea... 
Is this issue/situation hopeless?
take care Tom

**Comment by tompok76** [comment]
oh sorry for that big font, its due to it keeps formating :(

**Comment by hoyinm14mc** [comment]
Is v2.1.2 the first version of the plugin you used?

**Comment by hoyinm14mc** [comment]
Oh! I've figured out the problem. I'll release a new build very soon.
