### ISSUE TITLE
keep spamming console

### ISSUE THREAD

**Issue by CraftingMania** [CyberCube-hk/Jail#3]
it keep saying player move event hancups error something like that

**Comment by CraftingMania** [comment]
[14:41:28] [CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'Jail v1.1.0': Undefined property: hoyinm14mc\jail\Jail::$handcuff on hoyinm14mc\jail\listeners\PlayerListener

**Comment by CraftingMania** [comment]
i am lucky i fixed it my self

**Comment by CraftingMania** [comment]
i am just reporting error

**Comment by hoyinm14mc** [comment]
If you use the current source code updated about 23 hours ago, you'll find that the error is fixed. (Load it with DevTools !) ;)

**Comment by CraftingMania** [comment]
THX THATS BETTER THAN WHAT I DO

**Comment by hoyinm14mc** [comment]
@CraftingMania use the release 'v1.1.0'
