### ISSUE TITLE
How 'bout a way to override the "always-spawn" plugin or plugin's features?

### ISSUE THREAD

**Issue by daany123** [CyberCube-hk/Jail#4]
In some server, the "always-spawn" plugin is used to keep some minor bug or help new member to get to the things they need easily when they just done their login job. But, it had stop this plugin from doing their job: keep the player in jail. So please, add the "Override always spawn plugins" feature to your plugin, so that all of the server can get benefits from this plugin. Thanks for reading :smile:

**Comment by hoyinm14mc** [comment]
So then players won't be jailed after overridding right?

**Comment by daany123** [comment]
After overriding, the player will still in jail but if the player exit the game and get back into the server, it will teleport the player back to the jail instead of being teleport to the spawn place (which as the result of setting up the always-spawn plugins)

**Comment by hoyinm14mc** [comment]
I think I'll add it soon

**Comment by hoyinm14mc** [comment]
The feature is added in versions above 2.2.0
