### ISSUE TITLE
Gliches

### ISSUE THREAD

**Issue by astersx** [CyberCube-hk/Jail#6]
1. Players can vote ops!!
2. Players can vote a person every 40-50 seconds,  i put 50 minutes and no use!!!
3. Feature request,  prison borders,  to pull back hackers if they escape!!
4. This plugin is too awesome,  :3

**Comment by astersx** [comment]
forgot 5. Add sign with info about bail,  like how much he need pay!!

**Comment by astersx** [comment]
6. Some players get infinite time after jail out :0

**Comment by hoyinm14mc** [comment]
About the feature requests, those are already made by me and ready to be released very soon.
About 'players can vote OP': okay I'll fix it.
About 'players can vote after 40-50 secs': Really? I've tested it before! Okay I'll have a look into the code

**Comment by hoyinm14mc** [comment]
Btw.. Infinite time jail?? I don't seem to see that bug
