### ISSUE TITLE
Leak memory!! And more

### ISSUE THREAD

**Issue by astersx** [CyberCube-hk/Jail#7]
It seems  , this plugin make my server to use 2.6gb ram and crashed due to memory limkt, i allocated 4gb,  then again stop . If you run a serious server dont use this plugin. It will get 1 star and warning.
Dam, i was so excited about it T.T!!!!!!!

**Comment by hoyinm14mc** [comment]
I'm sorry to here about that.. As my plugin uses 3 repeating task to make sure the prisoner couldn't escape and provide the beautiful digital clock on the player's screen XD.
Anyways, I'll try to fix it

**Comment by astersx** [comment]
You should put players inside a border + players can escape if using mods,  tested.

**Comment by hoyinm14mc** [comment]
@astersx try v2.0.0 you can protect an area. A border will be set automatically, and players couldn't escape from it

**Comment by astersx** [comment]
I understand is great,  but i use 30+ plugins,  and this one cause high loads,  so i wait for a lighter version :)

**Comment by hoyinm14mc** [comment]
Oh I see

**Comment by astersx** [comment]
My server sometimes get full 63/63 players,  and i use many plugins so,  wen a light version of jail will be done? 😄

**Comment by NML32** [comment]
I just noticed my CPU stays at 100% while people are jailed.

**Comment by astersx** [comment]
Someone i know used jail!!  I warned him!!  And his Server Timed out,  it freeze!!!  =)))

**Comment by hoyinm14mc** [comment]
The Jail plugin is recommended to be used when your server is hosted through an online hosting provider, or when you have a great CPU.
