### ISSUE TITLE
Plugin is too heavy

### ISSUE THREAD

**Issue by Gamecrafter** [CyberCube-hk/Jail#8]
I've noticed many users are complaining about how much space this plugin takes up. It's possible to lighten up the plugin. @hoyinm14mc Do you want to work on that?

**Comment by hoyinm14mc** [comment]
The plugin is originally 153 kb, but after using pmt.mcpe.me (@Pemapmodder), the size was being multiplied..

**Comment by Gamecrafter** [comment]
Do you just directly build a PHAR using the exact files in the repo?

**Comment by PEMapModder** [comment]
What?
My website should only at most add a file of size less than 4kb, to label that the file is built by the website, as well as phar metadata.

**Comment by hoyinm14mc** [comment]
@PEMapModder then idk why..

**Comment by Gamecrafter** [comment]
@hoyinm14mc The plugin simply has too many files. I recommend shrinking down the plugin, while keeping as many features as possible.

**Comment by PEMapModder** [comment]
Do you have a sample to analyze?

**Comment by Gamecrafter** [comment]
@PEMapModder What do you mean by a sample? PHARs?

**Comment by hoyinm14mc** [comment]
But EssentialsPE has much files than Jail

**Comment by Gamecrafter** [comment]
That's because it has many functionalities. It would make sense for a plugin like that to have that many files.

**Comment by hoyinm14mc** [comment]
Look at this: https://github.com/matejdro/Jail
It's a bukkit famous Jail plugin, and it has much files than mine as well

**Comment by PEMapModder** [comment]
@hoyinm14mc it's normal for Java to have more files than PHP. Java is type-strict, so you have to create classes for many things (just look at the filenames). Also, more systematic-looking.

**Comment by hoyinm14mc** [comment]
Oic

**Comment by Gamecrafter** [comment]
Anyways if you want to we can start lighting up the plugin.

**Comment by hoyinm14mc** [comment]
Ok after my next commit

**Comment by hoyinm14mc** [comment]
@Gamecrafter Why reopen this? The plugin has been lightweighted from 482kb to 156kb
