### ISSUE TITLE
Please  implement with uuid.

### ISSUE THREAD

**Issue by Lucario2** [CyberCube-hk/Jail#9]
Please reprogram the plugin so that it recognizes the person by the uuid and not the subnet. Thanks in advanced.

**Comment by hoyinm14mc** [comment]
Thanks for the suggestion. I'll make it UUID and Subnet compatible and you can set them optionally.

**Comment by Lucario2** [comment]
Your welcome! And thanks for taking the time to program them, as most
developers are usually busy somewhat,
